[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes ",
    "apt-get update && apt-get install -y pkg-config libudev-dev:$CROSS_DEB_ARCH"
]

[target.arm-unknown-linux-gnueabi]
pre-build = [
    "apt-get update && apt-get install -y pkg-config wget",
    "wget https://raw.githubusercontent.com/cross-rs/wiki_assets/refs/heads/main/FAQ/Debian%20Repositories/install-deb.sh",
    "sed -i 's/http:\\/\\/security.debian.org\\/ buster\\/updates/https:\\/\\/security.debian.org\\/debian-security bookworm-security/g' install-deb.sh",
    "sed -i 's/buster/bookworm/g' install-deb.sh",
    "sed -i 's/archive-key-{7.0,8,9,10}.asc/archive-key-{10,11,12}.asc/g' install-deb.sh",
    "sed -i 's/archive-key-{8,9,10}-security.asc/archive-key-{10,11,12}-security.asc/g' install-deb.sh",
    "sed -i 's/release-{7,8,9,10}.asc/release-{10,11,12}.asc/g' install-deb.sh",
    "sed -i 's/archive_{2020,2021,2022}.key/archive_2025.key/g' install-deb.sh",
    "chmod +x install-deb.sh",
    "bash install-deb.sh $CROSS_DEB_ARCH libudev-dev",
    "apt-get install -y libc6-dev-armel-cross"
]