[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes ",
    "apt-get update && apt-get install -y pkg-config libudev-dev:$CROSS_DEB_ARCH"
]

[target.arm-unknown-linux-gnueabihf]
pre-build = [
    "apt-get update && apt-get install -y pkg-config wget",
    "wget https://raw.githubusercontent.com/cross-rs/wiki_assets/refs/heads/main/FAQ/Debian%20Repositories/install-deb.sh",
    "chmod +x install-deb.sh",
    "bash install-deb.sh $CROSS_DEB_ARCH libudev-dev"
]

[target.arm-unknown-linux-gnueabi]
pre-build = [
    "apt-get update && apt-get install -y pkg-config wget",
    "wget https://raw.githubusercontent.com/cross-rs/wiki_assets/refs/heads/main/FAQ/Debian%20Repositories/install-deb.sh",
    "chmod +x install-deb.sh",
    "bash install-deb.sh $CROSS_DEB_ARCH libudev-dev"
]